name: Text2SQL
description: "Build a CHAT application to ask questions about your database that will generate SQL query."
author: "Dhananjay"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
    OPENAI_API_KEY:
        description: "OpenAI api key to use for text-to-SQL conversion. Provided by CDP."
        required: true

    OPENAI_CHAT_MODEL:
        description: "OpenAI Chat Model to use for text-to-SQL conversion. Provided by CDP."
        required: true
        
    HR_USER:
        description: "HR database username. Provided by CDP."
        required: true
    HR_PASSWORD:
        description: "HR database password. Provided by CDP."
        required: true
    HR_DSN:
        description: "HR database DSN. Provided by CDP."
        required: true
        
    BANK_USER:
        description: "Banking database username."
        required: true
        
    BANK_PASSWORD:
        description: "Banking database password."
        required: true
        
    BANK_DSN:
        description: "Banking database DSN."
        required: true

    MUSIC_USER:
        description: "Music database username."
        required: true
        
    MUSIC_PASSWORD:
        description: "Music database password."
        required: true
    
    MUSIC_DSN:
        description: "Music database DSN."
        required: true

    WATERFALL_USER:
        description: "Waterfall database username."
        required: true
        
    WATERFALL_PASSWORD:
        description: "Waterfall database password."
        required: true
        
    WATERFALL_DSN:
        description: "Waterfall database DSN."
        required: true

    CHUNK_SIZE:
        default: "1024"
        description: "Chunk size for document processing."
        required: false
        
    CHUNK_OVERLAP:
        default: "64"
        description: "Chunk overlap for document processing."
        required: false

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard
