apiVersion: v1
kind: Service
metadata:
  name: text2sql-service
spec:
  type: LoadBalancer # Or NodePort, depending on your CDP environment
  selector:
    app: text2sql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501 # Streamlit Port
      name: frontend
    - protocol: TCP
      port: 8080
      targetPort: 8080  # FastAPI backend Port
      name: backend
